<?php

return $lang=array(
		//Common
		"AT"=>"a las",
		"BY"=>"por",
		"SELECT_ONE"=>"Seleccione una opción",
		"ALL_MALE"=>"Todos",
		"ALL_FEMALE"=>"Todas",
		"NOTHING"=>"Nada",
		"ORDER_BY"=>"Ordenar por",
		"SONGS"=>"canciones",
		//Menu
		"HELP_US"=>"Ayudanos a mantener el servidor realizando una donación de al menos 1€",
		"MENU_SONGS"=>"Canciones",
		"MENU_CONTEST"=>"Concursos",
		"MENU_PROGRAMS"=>"Programas y complementos",
		"MENU_TUTORIALS"=>"Tutoriales",
		"MENU_FORUM"=>"Foro",
		//Home
		"NEWS"=>"Noticias",
		"READ_MORE"=>"Leer más",
		//Songs
		"DOWNLOAD_SONGS"=>"Descargar canciones",
		"DOWNLOAD_TEXT"=>"Para buscar canciones puedes hacerlo por la letra inicial del artista, haciendo clic en las letras que hay sobre estas líneas, utlizando el buscador rápido que hay debajo o utilizando el buscador avanzado de la derecha con cualquiera de las opciones que tiene.",
		"DOWNLOAD_TEXT2"=>"Si quieres abrir las descargas en una nueva pestaña del navegador haz clic en el enlace de descarga con el botón central del ratón (el de la rueda). Si tienes alguna duda sobre el sistema lee",
		"HOW_DOWNLOAD_SONGS"=>"¿Cómo descargo las canciones?",
		"DOWNLOAD_TEXT3"=>". Si quieres utilizar el programa",
		"DOWNLOAD_TEXT4"=>"Jdownloader para bajarlas más cómodamente o todas de una vez",
		"DOWNLOAD_TEXT5"=>"solo tienes que hacer clic en el icono que hay a la derecha y seleccionar las que quieras. Si tienes dudas sobre su funcionamiento lee el tutorial",
		"DOWNLOAD_JDOWNLOADER"=>"Descargar canciones con jDownloader",
		"SHOW_WEEK"=>"Por semana de subida",
		"VIEW_WEEK"=>"Ver canciones clasificadas por semana de subida a la web",
		"VIEW_LAST_DOWNLOAD"=>"Ver las canciones que se han subido desde la última descarga que realizaste",
		"VIEW_NOT_DOWNLOAD_OR_MARKED"=>"Ver las canciones que todavia no has descargado ni marcado como descargadas",
		"SHOW_LAST_MONTH"=>"Más descargadas del último mes",
		"VIEW_LAST_MONTH"=>"Ver las canciones más descargadas del último mes",
		"SHOW_LAST_WEEK"=>"Más descargadas de la última semana",
		"VIEW_LAST_WEEK"=>"Ver las canciones más descargadas de la última semana",
		"SHOW_LAST_DAY"=>"Más descargadas de las últimas 24 horas",
		"VIEW_LAST_DAY"=>"Ver las canciones más descargadas de las últimas 24 horas",
		"SHOW_LAST_SONGS"=>"Mostrando las %d últimas canciones añadidas",
		"VIEW_SONGS_OF"=>"Ver todas las canciones para UltraStar de %s",
		"UPLOADED_BY"=>"Subida por %s el %s a las %s",
		"REVIEWED_BY"=>"y revisada por",
		"ENABLE_JDOWNLOADER"=>"Activar descarga de canciones a través de jDownloader",
		"VIEW_LANGUAGE"=>"Ver todas las canciones para UltraStar en %s",
		"VIEW_SIMILAR_ARTIST"=>"Ver artistas similares",
		"HAVE_VIDEO"=>"Tiene video",
		"HAVE_GOLDEN_NOTES"=>"Tiene notas doradas",
		"VIEW_MULTIPLAYER"=>"Ver todas las canciones para UltraStar con versión multijugador",
		"VIEW_SCORES"=>"Ver puntuaciones."
		"VALIDATE"=>"Esta canción ha sido validada y apenas contiene errores",
		"NOT_VALIDATE"=>"Esta canción puede contener errores sobre todo de sincronización que impiden obtener la máxima puntuación posible",
		"BRONZE_STAR"=>"Pueden hacerse hasta 9500 puntos en nivel fácil, 8000 en normal o 6000 en difícil",
		"SILVER_STAR"=>"",
		"GOLDEN_STAR"=>"",
		"VIEW_YEAR"=>"Ver todas las canciones para UltraStar del año %s",
		"DOWNLOAD"=>"Descargar",
		"DOWNLOAD_SONG"=>"Descargar %s- %s para el UltraStar",
		"DOWNLOADS"=>"descargas",
		"DOWNLOADS_LAST_MONTH"=>"el último mes",
		"DOWNLOADS_LAST_WEEK"=>"la última semana",
		"DOWNLOADS_LAST_DAY"=>"en las últimas 24 horas",
		//Song menu
		"VIEW_PLAYLIST"=>"Ver listas de reproducción",
		"VIEW_REQUESTED_SONG"=>"Ver listado de canciones pedidas",
		"REQUEST_SONGS"=>"Pedir canciones",
		"UPLOAD_SONGS"=>"Subir canciones nuevas",
		"SYLLABLES_SPLITTER_SONGS"=>"Silabeador de canciones",
		"REPAIR_SONGS"=>"Reparador de canciones",
		"INSERT_SONGS"=>"Insertar canciones nuevas",
		//Song search
		"SONG_ARTIST_DESCRIPTION"=>"Canción o artista o descripción",
		"ARTIST"=>"Artista",
		"SONG"=>"Cancion",
		"EDITION"=>"Edición",
		"WITHOUT_EDITION"=>"Sin edición",
		"PLAYLIST"=>"Lista de reproducción",
		"LANGUAGE"=>"Idioma",
		"YEAR"=>"Año",
		"WITHOUT_YEAR"=>"Sin año",
		"UPLOAD_WEEK"=>"Semana de subida",
		"WEEK_OF"=>"Semana del %s",
		"CREATOR"=>"Creador",
		"SHOW_SONGS"=>"Mostrar canciones",
		"NOT_DOWNLOADED"=>"No descargadas",
		"NOT_MARKED"=>"ni marcadas",
		"DOWNLOADED"=>"Descargadas",
		"MARKED"=>"Marcadas como descargadas",
		"FROM_LAST_DOWNLOAD"=>"Desde mi última descarga",
		"NONE"=>"Nada",
		"TOTALS"=>"totales",
		"DATE"=>"Fecha",
		"SIZE"=>"Tamaño",
		"VALIDATION"=>"Validación",
		"ACKNOWLEDGEMENTS"=>"Agradecimientos",
		"AVAILABITY"=>"Disponibilidad",
		"MULTIPLAYER"=>"Multijugador",
		"UP"=>"ascendente",
		"DOWN"=>"descendente",
		"SEARCH"=>"Buscar",
		"RESET"=>"Reiniciar",
		//Playlist
		"LAST_PLAYLIST"=>"Últimas %d listas actualizadas",
		"PLAYLIST_SONGS"=>"Listas de reproducción de canciones",
		"DOWNLOAD_LIST"=>"Descargar la lista %s",
		"SEARCH_SONGS_PLAYLIST"=>"Buscar todas las canciones que se incluyen en esta lista",
		//Playlist menu
		"VIEW_ALL_PLAYLIST"=>"Ver todas las listas de reproducción",
		"VIEW_MY_PLAYLIST"=>"Ver mis listas de reproducción",
		"CREATE_NEW_PLAYLIST"=>"Crear nueva lista de reproducción",
		"IMPORT_PLAYLIST"=>"Importar lista de reproducción",
		//My playlists
		"MY_PLAYLISTS"=>"Mis listas de reproducción",
		"MY_PLAYLISTS_TEXT"=>"Si quieres añadir canciones a tu lista de reproducción solo tienes que pulsar en el candado para abrirla y luego ir a la sección de canciones y seguir las instrucciones que aparecen arriba ¡Es muy sencillo!",
		"CLOSED_PLAYLIST"=>"Lista cerrada. Haz clic para abrirla y añadir canciones",
		"OPEN_PLAYLIST"=>"Lista abierta, puedes añadir canciones. Haz clic para cerrarla",
		"DOWNLOAD_PLAYLIST"=>"Descargar la lista %s",
		"DELETE_PLAYLIST"=>"Borrar lista",
		"DELETE"=>"Borrar %s",
		"CREATED_BY"=>"Creada por %s el %s",
		//New playlist
		"NEW_PLAYLIST"=>"Nueva lista de reproducción de canciones",
		"NEW_PLAYLIST_TEXT"=>"Introduce un nombre y una descripción de las canciones que va a contener la lista. Estos datos no los podrás volver a modificar, asi que procura que sean lo más descriptivos posible.",
		"PLAYLIST_NAME"=>"Nombre de la lista",
		"PLAYLIST_DESCRIPTION"=>"Descripción del contenido de la lista",
		"PLAYLIST_CATEGORY"=>"Categoría para la lista",
		"CREATE_PLAYLIST"=>"Crear lista",
		//Import playlist
		"IMPORT_PLAYLIST"=>"Importar una lista de reproducción",
		"IMPORT_PLAYLIST_TEXT"=>"Si tienes creadas listas de reproducción en tu Ultrastar puedes importarlas aqui para compartirlas con los demas usuarios. Solo tienes que elegir el archivo de la lista y poner una descripción, se añadirán solo las canciones que coincidan con las existentes en la base de datos",
		"PLAYLIST_FILE"=>"Archivo de la lista de reproducción",
		"IMPORT"=>"Importar",
		//Requested songs
		"LIST_REQUESTED_SONGS"=>"Lista de canciones pedidas",
		"REQUESTED_SONGS_TEXT"=>"Estas son las canciones que han ido pidiendo los usuarios de UltraStar España",
		"REQUESTED_SONGS_TEXT2"=>"Si querías pedir una canción y alguien lo ha hecho antes, puedes votarla para indicarlo. Así los creadores pueden ver las canciones que más quiere la gente e intentarán hacerlas antes si son de su agrado.",
		"VOTES_WEEK"=>"Te quedan %d voto/s esta semana",
		"SHOW_REQUESTED_SONGS"=>"Mostrando las %d peticiones realizadas la última semana",


		//Contest
		"SCORES_OF_SONGS"=>"Puntuaciones de canciones",
		"SCORES_TEXT"=>"Ahora puedes enviar tus puntuaciones para comparar tu nivel con el resto de usuarios de Ultrastar España.",
		"SCORES_TEXT2"=>"Para hacerlo puedes seguir el siguiente tutorial",
		"TUTORIAL_CONTEST"=>"tutorial para participar en los concursos",
		//Programs
		"PROGRAMS_ACCESSORIES"=>"Programas y complementos (carátulas, plugins y temas)",
		"COVERS"=>"Carátulas",
		"PROGRAMS"=>"Programas",
		"PROGRAMS_SONG"=>"Programas para la creación de canciones",
    );
